version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - loki

  grafana:
    image: grafana/grafana:master
    ports:
      - "3000:3000"
    networks:
      - loki

  nginx:
    image: wancloudsinc/netorc-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    links:
      - grafana
      - loki
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

